# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5dee25ffb8095ad930bbb07329b5813b"
application_url = "https://v0-testapp.vercel.app/"
embedded = true
name = "2025apptest"
handle = "2025apptest"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://v0-testapp.vercel.app/auth/callback",
  "https://v0-testapp.vercel.app/auth/shopify/callback",
  "https://v0-testapp.vercel.app/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "redefinetest.myshopify.com"
automatically_update_urls_on_dev = true
